Server:
  Model:    debug        #运行模式 debug测试环境  release生产环境
  Port:     8001         #监听端口
  ReadTimeout:  60       #
  WriteTimeout: 60       #



Upload:
  UploadMaxSize:  5     #MB
  UploadPath:     resource/uploads/video  #文件上传目录
  SaveSameFile:   true   #保留相同文件名的文件    
  Url:            /uploads   
  AllowExts:     #允许上传文件的后缀名
    - .jpg
    - .png
    - .jpeg
    - .zip
    - .xlsx
    - .doc
    - .docx
Mysql:
  Username:     root    #用户名
  Password:     root    #密码
  Host:         127.0.0.1:3306
  DBName:       blog        #数据库名称
  TablePrefix:  blog_        #数据库表名前缀
  Charset:      utf8    #链接字符格式
  ParseTime:    True
  MaxIdleConns: 10
  MaxOpenConns: 30

Redis:
  Addr:         127.0.0.1:6379 #地址
  Password:                   #密码
  DB:           0             #数据库
Captcha:
  UseRedis:     True   #是否开启redis保存验证码，默认验证码最大保存数量10000个
  PreKey:       captcha_ #验证码id存储前缀
  Expiration:   600   #验证码存活时间
  Height:       60    #验证码图片高度
  Width:        120   #验证码图片宽度
  Length:       5     #验证码长度
  MaxSkew:      0.2   #倾斜角度
  DotCount:     50    #杂点数量

JWT:                  #jwt认证令牌
  Secret:       gowebs
  Issuer:       xfdada
  Expire:      7200
